'use client';

import React, { useEffect, useState } from 'react';

/**
 * NewspaperView Component
 * Renders the full newspaper HTML generated by Python within an iframe.
 */
const NewspaperView = () => {
    const [html, setHtml] = useState('');
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);

    useEffect(() => {
        const fetchNewspaper = async () => {
            try {
                const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001';
                const response = await fetch(`${baseUrl}/api/templates/latest/diario`);
                const result = await response.json();
                
                if (result.success && result.data && result.data.html) {
                    setHtml(result.data.html);
                } else {
                    setError('No se pudo cargar el diario');
                }
            } catch (err) {
                console.error('Error fetching newspaper:', err);
                setError('Error en la conexión con el servidor');
            } finally {
                setLoading(false);
            }
        };

        fetchNewspaper();
    }, []);

    if (loading) return (
        <div className="max-w-7xl mx-auto px-4 py-12 flex justify-center">
            <div className="animate-pulse flex flex-col items-center">
                <div className="h-8 w-64 bg-gray-200 rounded mb-8"></div>
                <div className="h-[600px] w-full max-w-4xl bg-gray-100 rounded-3xl"></div>
            </div>
        </div>
    );
    
    if (error || !html) return null;

    return (
        <section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12" id="diario-digital">
            <div className="flex flex-col items-center">
                <div className="inline-flex items-center gap-2 px-4 py-1.5 bg-blue-50 text-blue-600 rounded-full text-xs font-bold uppercase tracking-widest mb-4 border border-blue-100">
                    <span className="relative flex h-2 w-2">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
                        <span className="relative inline-flex rounded-full h-2 w-2 bg-blue-500"></span>
                    </span>
                    Edición de Hoy
                </div>
                
                <h2 className="text-4xl font-black text-gray-900 mb-2 tracking-tight text-center">
                    Diario <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600">Digital IA</span>
                </h2>
                <p className="text-gray-500 mb-10 text-center max-w-2xl font-medium">
                    Tu dosis diaria de noticias tecnológicas curadas y maquetadas automáticamente por inteligencia artificial.
                </p>

                <div className="w-full bg-gray-100 rounded-[2.5rem] overflow-hidden shadow-[0_30px_60px_-15px_rgba(0,0,0,0.15)] border-8 border-white p-1 relative group">
                    <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-black/5 pointer-events-none z-10"></div>
                    
                    <iframe
                        srcDoc={html}
                        className="w-full min-h-[880px] border-none rounded-[1.8rem] bg-white"
                        title="Diario Brief AI News"
                        loading="lazy"
                        sandbox="allow-scripts allow-same-origin"
                    />
                    
                    {/* Bottom fade shadow for depth */}
                    <div className="absolute bottom-0 left-0 right-0 h-20 bg-gradient-to-t from-gray-900/10 to-transparent pointer-events-none"></div>
                </div>

                <div className="mt-8 flex flex-col items-center gap-4">
                    <div className="flex -space-x-2">
                        {[1, 2, 3, 4].map((i) => (
                            <div key={i} className="w-8 h-8 rounded-full border-2 border-white bg-gray-200" />
                        ))}
                        <div className="w-8 h-8 rounded-full border-2 border-white bg-blue-600 flex items-center justify-center text-[10px] font-bold text-white">
                            +1k
                        </div>
                    </div>
                    <p className="text-sm text-gray-400 font-medium">
                        Disfrutado por miles de suscriptores cada mañana
                    </p>
                </div>
            </div>
            
            <style jsx>{`
                #diario-digital {
                    perspective: 1000px;
                }
            `}</style>
        </section>
    );
};

export default NewspaperView;
